#  Copyright 2021-present, the Recognai S.L. team.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

"""edit users table

Revision ID: 0338f9e3d807
Revises: 1e629a913727
Create Date: 2023-09-07 19:38:40.432727

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0338f9e3d807"
down_revision = "1e629a913727"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "show_discard_button")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("show_discard_button", sa.BOOLEAN(), server_default=sa.text("1"), nullable=False))
    # ### end Alembic commands ###
