"""add discard button check to user

Revision ID: fec1b59da7c7
Revises: 1e629a913727
Create Date: 2023-09-20 15:09:08.376198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec1b59da7c7'
down_revision = '1e629a913727'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('show_discard_button', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_discard_button')
    # ### end Alembic commands ###
